name: "☀️ Daily"
description: "오늘의 목표와 할 일을 공유합니다."
title: "[Daily] "
category: "daily (이하연)" 
body:
  - type: textarea
    id: goal
    attributes:
      label: "🎯 오늘 목표"
      description: "오늘의 핵심 목표를 간략히 적어주세요."
    validations:
      required: true
  - type: textarea
    id: issues
    attributes:
      label: "📌 오늘 할 이슈"
      value: |
        - **동현:** 
        - **동훈:**
        - **정민:**  
        - **종호:** 
        - **하연:** 
    validations:
      required: true