name: "🤝 Planning Meeting"
description: "기획 회의 내용을 기록하고 결정사항을 공표합니다."
title: "[PLAN] "
labels: 
body:
  - type: textarea
    id: discussions
    attributes:
      label: "🗣 논의 사항"
      description: "회의 중 논의된 주요 안건들을 기록해 주세요."
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
      
  - type: textarea
    id: decisions
    attributes:
      label: "✅ 결정 사항"
      description: "최종적으로 합의되고 결정된 사항(Action Item)을 명확히 기록해 주세요."
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

